name: Run stuff in a container

on:
  push:
    paths:
      - .github/workflows/docker.yaml

jobs:
  run_something_in_container:
    name: Run in Container
    runs-on: ubuntu-latest
    container:  # will be used for each step now; can probably ba added to each step as well -- see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
      image: archlinux
      options: -v "${{ github.workspace }}:/workspace"
      # Note: using volumes did not work, so using this workaround
      #       see https://stackoverflow.com/a/60202672/2165903
    # This job runs on Linux
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pacman -Sy --noconfirm tree
      - name: get issue
        run: cat /etc/issue > /workspace/tree.txt
      - name: list /workspace
        run: tree /workspace >> /workspace/tree.txt
      - name: Upload the tree listing
        uses: actions/upload-artifact@v1
        with:
          name: tree-listing
          path: "${{ github.workspace }}/tree.txt"
