name: Repository Release
on: [push]

# push to a single release which should only contain the latest and greatest data

jobs:
  build:
    name: Repository Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Create an asset with changing name
        run: echo content of run ${{ github.run_number }} > ${{ github.workspace }}/content-${{ github.run_number }}.txt
      - name: Create an asset with fixed name
        run: echo this release contains content-${{ github.run_number }}.txt > ${{ github.workspace }}/index.txt

      - name: Remove the release with the tag
        uses: kopp/action-delete-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: repository

      - name: create release and add files
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: repository
          name: build ${{ github.run_number}} for ${{ github.ref }} (${{ github.sha }}) which will use the same tag as always...
          body: |
            The latest and greatest stuff (and only that) is in here...
            Now with the content from build ${{ github.run_number }}.
            It should contain
            file index.txt
            file content-${{ github.run_number }}.txt
          files: |
            ${{ github.workspace }}/content-${{ github.run_number }}.txt
            ${{ github.workspace }}/index.txt
          draft: false
          prerelease: false
