name: Repository Release
on: [push]

# push to a single release which should only contain the latest and greatest data

jobs:
  build:
    name: Repository Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Create an asset with changing name
        run: echo content of run ${{ github.run_number }} > ${{ github.workspace }}/content-${{ github.run_number }}.txt
      - name: Create an asset with fixed name
        run: echo this release contains content-${{ github.run_number }}.txt > ${{ github.workspace }}/index.txt

      - name: Remove the release with the tag
        uses: kopp/action-delete-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TAG_NAME: repository

      - name: Create a release with always the same tag
        id: create_release
        # this id is used later to access output produced by this action
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: repository
          release_name: build ${{ github.run_number}} for ${{ github.ref }} (${{ github.sha }}) which will use the same tag as always...
          body: |
            The latest and greatest stuff is in here...
            Now with the content from build ${{ github.run_number }}.
            It should contain
            file index.txt
            file content-${{ github.run_number }}.txt
          draft: false
          prerelease: false

      - name: add asset content-${{ github.run_number }} to the release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/content-${{ github.run_number }}.txt
          asset_name: content-${{ github.run_number }}.txt
          asset_content_type: text/plain

      - name: add asset index.txt the release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/index.txt
          asset_name: index.txt
          asset_content_type: text/plain

          # alternative maybe?
#      - name: create release and add files directly
#        uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          files: |
#            ${{ github.workspace }}/content-${{ github.run_number }}.txt
#            ${{ github.workspace }}/index.txt

      #- name: remove an old release
        # github api for apps allows to do "DELETE /repos/:owner/:repo/releases/:release_id" to delete a release
        # there is an action, https://github.com/ame-yu/action-delete-latest-release that deletes the last release
